pipelines:
  restbucks-bff-wechatstore-uat: 
    group: restbucks-wechatstore
    materials:
      src: 
        git: https://github.com/restbucks/restbucks-bff-wechatstore-pipeline.git
        branch: master
      mydependency:
        pipeline: restbucks-bff-wechatstore
        stage: commit  
    stages:
      - deploy: 
          jobs:
            deploy:
              tasks:
               - fetch:
                   pipeline: restbucks-bff-wechatstore
                   stage: commit
                   job: build
                   source: build/libs/*.jar
                   destination: build/libs
